### ISSUE TITLE
New snippets

### ISSUE THREAD

**Issue by yannux** [pipe-devnull/ZF2Helper#3]
Hi,

New in github contribution, I've forked your repositories and added first draft for new snippets.
Will you interested about merging later ?

Thanks for ZF2Helper ! :)

**Comment by pipe-devnull** [comment]
Hi,

Yes, when your ready with your extra snippets just open a pull request and I'll take a look at merging them in.  Contributions most welcome :)

Cheers, 
Ade

**Comment by yannux** [comment]
Thanks, just done it.

Cheers, 
Yann.
