### ISSUE TITLE
Compatibility with ST3

### ISSUE THREAD

**Issue by pipe-devnull** [pipe-devnull/ZF2Helper#4]
- Test plugin with ST3 
- Add to ST3 package repository

**Comment by MattDMo** [comment]
what's the status on this?

**Comment by jchlu** [comment]
ST3 compatibility would interest a large number of people no doubt.
Do you need test subjects?
Would be happy to beta and report any issues.

**Comment by anil3a** [comment]
Is it gonna be compatible or not? I am very interested in this plugin

**Comment by pipe-devnull** [comment]
Now compatible with ST3 (and backwards with ST2).  Just got to wait for update to go through with Package control.

**Comment by pipe-devnull** [comment]
Available via package control now
