### ISSUE TITLE
Not working on sublime text 3

### ISSUE THREAD

**Issue by lft-arjun** [pipe-devnull/ZF2Helper#8]
I tried to create module using zf2 helper but nothing is happen. Basically it doesn't work for me.

**Comment by pipe-devnull** [comment]
Thats not much info to work with .... I have not used this plugin for a while myself but I have given it a quick test on my two test machines and it works fine.  

If you provide detail of the steps you are taking then I might be able to help.

**Comment by lft-arjun** [comment]
Hey , When i trying to create the module it doesn't throw any error and doesn't create any things even not a empty folder inside modules. I don't know what going on there . Let's see on my machine that might help  you to figure out the problem. Could you please let me know your availability (my time zone is GMT+5).

**Comment by ghost** [comment]
Sorry for re-opening. I was facing the same problem with this plugin using Sublime Text 3 on Kubuntu 15.04. Sublime could not find the files contained in the repository's 'zf2-helper' folder. The solution was to download the files manually from the repository and place them inside '~/.config/sublime-text-3/Packages/PHP Zend Framework 2 Helper/zf2-helper'. Thanks for your plugin!

**Comment by kaidoj** [comment]
It din't work for me in windows but after i read @thokel  post i downloaded the repository and added directory to AppData\Roaming\Sublime Text 3\Packages\PHP Zend Framework 2 Helper\ and then added all files to that folder and voila it worked :) hope it helps someone.

**Comment by versedi** [comment]
I'm confirming that manually downloading and copying files into Sublime Text 3 AppData works on Windows. I suggest adding information to readme.

**Comment by ghost** [comment]
Hi, tried manually downloading and copying files into ST3. Creating module works perfectly fine but creating controller isn't. Here's the error log I got:

```
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\kyl.sanantonio\AppData\Roaming\Sublime Text 3\Packages\PHP Zend Framework 2 Helper\zf2-helper.py", line 78, in run
    self.module_name = os.path.split(self.viewfile)[0].split('/')[-2]
IndexError: list index out of range
```

I'm using ST3.2
